# Generated by Django 5.2.7 on 2025-10-21 06:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(default="Yajasa Technology", max_length=200),
                ),
                ("rut", models.CharField(default="77.182.974-0", max_length=20)),
                (
                    "direccion",
                    models.TextField(
                        default="Uribe 636 of 707, C. de Negocios, Antofagasta"
                    ),
                ),
                ("telefono", models.CharField(default="+569-42920058", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        default="Yajasa.technology@gmail.com", max_length=254
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(editable=False, unique=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("cliente_nombre", models.CharField(blank=True, max_length=200)),
                ("cliente_empresa", models.CharField(blank=True, max_length=200)),
                ("cliente_email", models.EmailField(blank=True, max_length=254)),
                ("cliente_telefono", models.CharField(blank=True, max_length=20)),
                (
                    "asunto",
                    models.CharField(default="Cotización de Servicios", max_length=200),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "tiempo_entrega",
                    models.CharField(
                        default="1 Día, Esperando que la oferta sea de su aceptación",
                        max_length=200,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                ("actualizada_en", models.DateTimeField(auto_now=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cotizacion.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_numero", models.PositiveIntegerField()),
                (
                    "cantidad",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("caracteristica", models.TextField()),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cotizacion.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Cotización",
                "verbose_name_plural": "Items de Cotización",
                "ordering": ["item_numero"],
                "unique_together": {("cotizacion", "item_numero")},
            },
        ),
    ]
