# Generated by Django 5.2.7 on 2025-10-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='asunto',
            new_name='detalle',
        ),
    ]
