# Generated by Django 5.2.7 on 2025-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_rename_asunto_cotizacion_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='detalle',
            new_name='asunto',
        ),
    ]
