# Generated by Django 5.2.7 on 2025-11-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_rename_detalle_cotizacion_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
