# Generated by Django 5.2.7 on 2025-11-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_cotizacion_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
