# Generated by Django 5.2.7 on 2025-11-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0005_cotizacion_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='pdf_file',
        ),
    ]
