# Generated by Django 5.2.7 on 2025-11-11 17:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_remove_cotizacion_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['empresa', 'nombre_contacto'],
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Mi Empresa', 'verbose_name_plural': 'Mi Empresa'},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='itemcotizacion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_direccion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_empresa',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente_telefono',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='cotizacion.cliente'),
        ),
        migrations.RemoveField(
            model_name='itemcotizacion',
            name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='itemcotizacion',
            name='item_numero',
        ),
        migrations.RemoveField(
            model_name='itemcotizacion',
            name='valor_unitario',
        ),
    ]
